export type Paper = {
  title: string;
  desc: string;
};

export type Project = {
  src: string;
  name: string;
  papers: Paper[];
};

export const projects: Project[] = [
  {
    src: "/project/raksha.png",
    name: "Raksha",
    papers: [
      { title: "Raksha", desc: "Revolutionizing personal safety" },
      { title: "Inspire", desc: "Advanced safety features" },
      { title: "Contributors", desc: "50" },
      { title: "Sponsor", desc: "10" },
      { title: "Investor", desc: "20,000 Dinars" },
      { title: "Issue", desc: "30 Dinars" },
      { title: "Valuation", desc: "100,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/plane.png",
    name: "Frnas",
    papers: [
      { title: "Frnas", desc: "Drone for the delivery of first aid" },
      { title: "Inspire", desc: "MQ-9" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "7" },
      { title: "Investor", desc: "10,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "80,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/sun.png",
    name: "Solar",
    papers: [
      { title: "Solar", desc: "Harnessing the power of the sun" },
      { title: "Inspire", desc: "Innovative solar solutions" },
      { title: "Contributors", desc: "35" },
      { title: "Sponsor", desc: "8" },
      { title: "Investor", desc: "15,000 Dinars" },
      { title: "Issue", desc: "25 Dinars" },
      { title: "Valuation", desc: "90,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/office.png",
    name: "Maktb",
    papers: [
      { title: "Maktb", desc: "Reimagining the workspace" },
      { title: "Inspire", desc: "Modern office designs" },
      { title: "Contributors", desc: "60" },
      { title: "Sponsor", desc: "12" },
      { title: "Investor", desc: "25,000 Dinars" },
      { title: "Issue", desc: "40 Dinars" },
      { title: "Valuation", desc: "120,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/alkhwarizmi.png",
    name: "Alkhwarizmi",
    papers: [
      { title: "Alkhwarizmi", desc: "Innovative AI solutions" },
      { title: "Inspire", desc: "Cutting-edge technology" },
      { title: "Contributors", desc: "28" },
      { title: "Sponsor", desc: "6" },
      { title: "Investor", desc: "12,000 Dinars" },
      { title: "Issue", desc: "22 Dinars" },
      { title: "Valuation", desc: "70,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/jena.png",
    name: "Jena",
    papers: [
      { title: "Jena", desc: "Eco-friendly products" },
      { title: "Inspire", desc: "Sustainable living" },
      { title: "Contributors", desc: "45" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "35 Dinars" },
      { title: "Valuation", desc: "95,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/databayt.png",
    name: "Databayt",
    papers: [
      { title: "Databayt", desc: "Data-driven solutions" },
      { title: "Inspire", desc: "Big data analytics" },
      { title: "Contributors", desc: "55" },
      { title: "Sponsor", desc: "11" },
      { title: "Investor", desc: "22,000 Dinars" },
      { title: "Issue", desc: "38 Dinars" },
      { title: "Valuation", desc: "110,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/hertz.png",
    name: "Hertz",
    papers: [
      { title: "Hertz", desc: "Innovative sound technology" },
      { title: "Inspire", desc: "High-fidelity audio" },
      { title: "Contributors", desc: "32" },
      { title: "Sponsor", desc: "7" },
      { title: "Investor", desc: "14,000 Dinars" },
      { title: "Issue", desc: "26 Dinars" },
      { title: "Valuation", desc: "85,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/biogas.png",
    name: "Biogas",
    papers: [
      { title: "Biogas", desc: "Clean energy solutions" },
      { title: "Inspire", desc: "Sustainable fuel" },
      { title: "Contributors", desc: "40" },
      { title: "Sponsor", desc: "8" },
      { title: "Investor", desc: "16,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/polymer.png",
    name: "Polymer",
    papers: [
      { title: "Polymer", desc: "Advanced material science" },
      { title: "Inspire", desc: "High-performance materials" },
      { title: "Contributors", desc: "37" },
      { title: "Sponsor", desc: "7" },
      { title: "Investor", desc: "13,000 Dinars" },
      { title: "Issue", desc: "24 Dinars" },
      { title: "Valuation", desc: "75,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/alshifaa.png",
    name: "Alshifaa",
    papers: [
      { title: "Alshifaa", desc: "Innovative healthcare" },
      { title: "Inspire", desc: "Medical advancements" },
      { title: "Contributors", desc: "58" },
      { title: "Sponsor", desc: "10" },
      { title: "Investor", desc: "21,000 Dinars" },
      { title: "Issue", desc: "34 Dinars" },
      { title: "Valuation", desc: "105,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/post.png",
    name: "Post",
    papers: [
      { title: "Post", desc: "Modern postal solutions" },
      { title: "Inspire", desc: "Efficient delivery systems" },
      { title: "Contributors", desc: "44" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "17,000 Dinars" },
      { title: "Issue", desc: "29 Dinars" },
      { title: "Valuation", desc: "92,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/mujadad.png",
    name: "Mujadad",
    papers: [
      { title: "Tjdeed", desc: "Reconditioning solutions" },
      { title: "Inspire", desc: "Green energy" },
      { title: "Contributors", desc: "36" },
      { title: "Sponsor", desc: "8" },
      { title: "Investor", desc: "15,000 Dinars" },
      { title: "Issue", desc: "27 Dinars" },
      { title: "Valuation", desc: "82,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/auto.png",
    name: "Auto",
    papers: [
      { title: "Auto", desc: "Automotive workshop" },
      { title: "Inspire", desc: "Smart vehicles" },
      { title: "Contributors", desc: "50" },
      { title: "Sponsor", desc: "10" },
      { title: "Investor", desc: "20,000 Dinars" },
      { title: "Issue", desc: "30 Dinars" },
      { title: "Valuation", desc: "100,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/hamari.png",
    name: "Hamari",
    papers: [
      { title: "Hamari", desc: "Agricultural advancements" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/hook.png",
    name: "Najil",
    papers: [
      { title: "Najil", desc: "Fishing technology" },
      { title: "Inspire", desc: "Sustainable fishing" },
      { title: "Contributors", desc: "34" },
      { title: "Sponsor", desc: "7" },
      { title: "Investor", desc: "14,000 Dinars" },
      { title: "Issue", desc: "23 Dinars" },
      { title: "Valuation", desc: "78,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/book.png",
    name: "Bookstore",
    papers: [
      { title: "Bookstore", desc: "Digital library platform" },
      { title: "Inspire", desc: "Knowledge sharing" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/dahab.png",
    name: "Dahab",
    papers: [
      { title: "Dahab", desc: "Gold trading platform" },
      { title: "Inspire", desc: "Financial technology" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/bullet.png",
    name: "Bullet",
    papers: [
      { title: "Bullet", desc: "Fast delivery service" },
      { title: "Inspire", desc: "Express logistics" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/mandeel.png",
    name: "Mendeal",
    papers: [
      { title: "Mendeal", desc: "E-commerce platform" },
      { title: "Inspire", desc: "Digital marketplace" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/lotion.png",
    name: "Lotion",
    papers: [
      { title: "Lotion", desc: "Natural skincare" },
      { title: "Inspire", desc: "Organic beauty" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/leather.png",
    name: "Leather",
    papers: [
      { title: "Leather", desc: "Premium leather goods" },
      { title: "Inspire", desc: "Artisanal crafts" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/tv.png",
    name: "Screen",
    papers: [
      { title: "Screen", desc: "Digital display solutions" },
      { title: "Inspire", desc: "Visual technology" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/souq.png",
    name: "Souq",
    papers: [
      { title: "Souq", desc: "Traditional marketplace" },
      { title: "Inspire", desc: "Cultural commerce" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/riche.png",
    name: "Riche",
    papers: [
      { title: "Riche", desc: "Wealth management" },
      { title: "Inspire", desc: "Financial planning" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/seed.png",
    name: "Seed",
    papers: [
      { title: "Seed", desc: "Agricultural innovation" },
      { title: "Inspire", desc: "Smart farming" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/peanut.png",
    name: "Peanut",
    papers: [
      { title: "Peanut", desc: "Food processing" },
      { title: "Inspire", desc: "Healthy snacks" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/tomato.png",
    name: "Salsa",
    papers: [
      { title: "Salsa", desc: "Food production" },
      { title: "Inspire", desc: "Fresh produce" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/semsem.png",
    name: "Semsem",
    papers: [
      { title: "Semsem", desc: "Food processing" },
      { title: "Inspire", desc: "Traditional foods" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/outdoor.png",
    name: "Outdoor",
    papers: [
      { title: "Outdoor", desc: "Adventure equipment" },
      { title: "Inspire", desc: "Outdoor activities" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/basketball.png",
    name: "Basketball",
    papers: [
      { title: "Basketball", desc: "Sports equipment" },
      { title: "Inspire", desc: "Sports innovation" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/volleyball.png",
    name: "Volleyball",
    papers: [
      { title: "Volleyball", desc: "Sports equipment" },
      { title: "Inspire", desc: "Sports innovation" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/soccer.png",
    name: "Soccer",
    papers: [
      { title: "Soccer", desc: "Sports equipment" },
      { title: "Inspire", desc: "Sports innovation" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/swim.png",
    name: "Swim",
    papers: [
      { title: "Swim", desc: "Sports equipment" },
      { title: "Inspire", desc: "Sports innovation" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/tennis.png",
    name: "Tennis",
    papers: [
      { title: "Tennis", desc: "Sports equipment" },
      { title: "Inspire", desc: "Sports innovation" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/snow.png",
    name: "Snow",
    papers: [
      { title: "Snow", desc: "Winter sports" },
      { title: "Inspire", desc: "Winter activities" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/alyamama.png",
    name: "Yamama",
    papers: [
      { title: "Yamama", desc: "Pigeon breeding" },
      { title: "Inspire", desc: "Traditional sports" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/smart.png",
    name: "Smart",
    papers: [
      { title: "Smart", desc: "Smart home solutions" },
      { title: "Inspire", desc: "Home automation" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/speaker.png",
    name: "Acoustic",
    papers: [
      { title: "Acoustic", desc: "Audio technology" },
      { title: "Inspire", desc: "Sound innovation" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/real-estate.png",
    name: "Estate",
    papers: [
      { title: "Estate", desc: "Real estate platform" },
      { title: "Inspire", desc: "Property management" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/school.png",
    name: "Madrsa",
    papers: [
      { title: "Madrsa", desc: "Educational platform" },
      { title: "Inspire", desc: "Digital learning" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/mosque.png",
    name: "Masjid",
    papers: [
      { title: "Masjid", desc: "Community center" },
      { title: "Inspire", desc: "Community service" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
  {
    src: "/project/visba.png",
    name: "Visba",
    papers: [
      { title: "Visba", desc: "Visual arts platform" },
      { title: "Inspire", desc: "Digital art" },
      { title: "Contributors", desc: "42" },
      { title: "Sponsor", desc: "9" },
      { title: "Investor", desc: "18,000 Dinars" },
      { title: "Issue", desc: "28 Dinars" },
      { title: "Valuation", desc: "88,000 Dinars" },
      { title: "Phase", desc: "Development" },
    ],
  },
];
