import {
  BookOpen,
  Bot,
  Calendar,
  FileText,
  Home,
  Info,
  Library,
  Lightbulb,
  UserPlus,
  Users,
  Video,
} from "lucide-react"

import type { SearchConfig } from "./types"

export const spmaSearchConfig: SearchConfig = {
  navigation: [
    {
      id: "home",
      title: "Home",
      type: "navigation",
      href: "/",
      icon: Home,
      keywords: ["main", "landing", "homepage"],
      breadcrumb: ["SPMA"],
    },
    {
      id: "about",
      title: "About",
      type: "navigation",
      href: "/about",
      icon: Info,
      keywords: ["about", "organization", "mission", "vision"],
      breadcrumb: ["SPMA"],
    },
    {
      id: "events",
      title: "Events",
      type: "navigation",
      href: "/events",
      icon: Calendar,
      keywords: ["events", "activities", "schedule", "calendar"],
      breadcrumb: ["SPMA"],
    },
    {
      id: "publications",
      title: "Publications",
      type: "navigation",
      href: "/publications",
      icon: FileText,
      keywords: ["publications", "papers", "research", "journal"],
      breadcrumb: ["SPMA"],
    },
    {
      id: "library",
      title: "Library",
      type: "navigation",
      href: "/library",
      icon: Library,
      keywords: ["library", "books", "resources", "references"],
      breadcrumb: ["SPMA"],
    },
    {
      id: "knowledge",
      title: "Knowledge",
      type: "navigation",
      href: "/knowledge",
      icon: Lightbulb,
      keywords: ["knowledge", "learning", "education", "wiki"],
      breadcrumb: ["SPMA"],
    },
    {
      id: "articles",
      title: "Articles",
      type: "navigation",
      href: "/article",
      icon: BookOpen,
      keywords: ["articles", "blog", "posts", "writing"],
      breadcrumb: ["SPMA", "Knowledge"],
    },
    {
      id: "videos",
      title: "Videos",
      type: "navigation",
      href: "/video",
      icon: Video,
      keywords: ["videos", "media", "watch", "stream"],
      breadcrumb: ["SPMA", "Knowledge"],
    },
    {
      id: "members",
      title: "Members",
      type: "navigation",
      href: "/members",
      icon: Users,
      keywords: ["members", "team", "people", "directory"],
      breadcrumb: ["SPMA"],
    },
    {
      id: "join",
      title: "Join",
      type: "navigation",
      href: "/members/join",
      icon: UserPlus,
      keywords: ["join", "register", "signup", "membership", "apply"],
      breadcrumb: ["SPMA", "Members"],
    },
    {
      id: "docs",
      title: "Docs",
      type: "navigation",
      href: "/docs",
      icon: FileText,
      keywords: ["documentation", "docs", "guide", "help"],
      breadcrumb: ["SPMA"],
    },
    {
      id: "chatbot",
      title: "Chatbot",
      type: "navigation",
      href: "/chatbot",
      icon: Bot,
      keywords: ["chatbot", "ai", "assistant", "chat", "help"],
      breadcrumb: ["SPMA"],
    },
  ],
  actions: [],
  settings: [],
  showRecent: true,
  maxRecent: 5,
}
